#!/bin/bash
#This bash script removes the extraneous files generated by xelatex. To run it simply use `bash -i clean_up.sh`
xelatex main.tex
bibtex main.aux
xelatex main.tex
xelatex main.tex
find . -name "*.aux" -type f -delete
rm main.!(tex|pdf)
